language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
      - pandoc
install:
  - pandoc -f markdown -t rst README.md > README.rst
  - python setup.py -q install
script: nosetests -s -v --with-coverage --cover-package=pysqldf --cover-html
cache: pip
sudo: false
